### ISSUE TITLE
where is bert_config.json ?

### ISSUE THREAD

**Issue by dataf3l** [kamalkraj/BERT-SQuAD#18]
Hi friends, I get this error:

Model name 'model/bert_config.json' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'model/bert_config.json' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File BERT-SQuAD/api.py", line 9, in <module>
    model = QA("model")
  File "BERT-SQuAD/bert.py", line 30, in __init__
    self.model, self.tokenizer = self.load_model(model_path)
  File "BERT-SQuAD/bert.py", line 40, in load_model
    config = BertConfig.from_pretrained(model_path + "/bert_config.json")
  File "venv/lib/python3.9/site-packages/pytorch_transformers/modeling_utils.py", line 194, in from_pretrained
    raise e
  File "BERT-SQuAD/venv/lib/python3.9/site-packages/pytorch_transformers/modeling_utils.py", line 180, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "BERT-SQuAD/venv/lib/python3.9/site-packages/pytorch_transformers/file_utils.py", line 124, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file model/bert_config.json not found

any suggestions?

**Comment by dataf3l** [comment]
ok never mind I found the file:

{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

it is found in the link on the README.
