### ISSUE TITLE
HOW TO GET "utils_squad_evaluate"

### ISSUE THREAD

**Issue by qiunlp** [kamalkraj/BERT-SQuAD#7]
THERE IS  "from utils_squad_evaluate import EVAL_OPTS, main as evaluate_on_squad"   IN  "run.squad.py"  ,  HOW TO GET "utils_squad_evaluate"?

**Comment by shinsei66** [comment]
> THERE IS "from utils_squad_evaluate import EVAL_OPTS, main as evaluate_on_squad" IN "run.squad.py" , HOW TO GET "utils_squad_evaluate"?

I've got the same error.

**Comment by sreejith3534** [comment]
https://github.com/nlpyang/pytorch-transformers/blob/master/examples/utils_squad_evaluate.py

@yzgdjqwh ,I guess you are looking for this ?

**Comment by shinsei66** [comment]
> https://github.com/nlpyang/pytorch-transformers/blob/master/examples/utils_squad_evaluate.py
> 
> @yzgdjqwh ,I guess you are looking for this ?

Thanks so much!

**Comment by shinsei66** [comment]
Another Error:
Maybe we don't need '["data"]'  within 'input_data = json.load(reader)["data"]'
```
Traceback (most recent call last):
  File "/kaggle/input/bert-squad/BERT-SQuAD-master/training/run_squad.py", line 527, in <module>
    main()
  File "/kaggle/input/bert-squad/BERT-SQuAD-master/training/run_squad.py", line 472, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False, output_examples=False)
  File "/kaggle/input/bert-squad/BERT-SQuAD-master/training/run_squad.py", line 288, in load_and_cache_examples
    version_2_with_negative=args.version_2_with_negative)
  File "/kaggle/input/bert-squad/BERT-SQuAD-master/training/utils_squad.py", line 114, in read_squad_examples
    input_data = json.load(reader)["data"]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
```
